### ISSUE TITLE
SSL Validity 

### ISSUE THREAD

**Issue by mizbanpaytakht** [dyaa/node-ssl-checker#12]
Hi,

How can I check the self-signed and valid SSL ?

**Comment by dyaa** [comment]
Yes, Please check [this](https://runkit.com/5b0d54870a9d4f00121e5a8d/5b83b75dd4aadd00126d88fe) demo

**Comment by mizbanpaytakht** [comment]
Hi,

But both there is no deference between self-signed and valid ssl !
